package com.miaww.demoapi.mapper;

import com.miaww.demoapi.model.MenuInfo;
import com.miaww.demoapi.model.MenuInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MenuInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIAWW.MENU_INFO
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    long countByExample(MenuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIAWW.MENU_INFO
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    int deleteByExample(MenuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIAWW.MENU_INFO
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    int deleteByPrimaryKey(String menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIAWW.MENU_INFO
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    int insert(MenuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIAWW.MENU_INFO
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    int insertSelective(MenuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIAWW.MENU_INFO
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    List<MenuInfo> selectByExample(MenuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIAWW.MENU_INFO
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    MenuInfo selectByPrimaryKey(String menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIAWW.MENU_INFO
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    int updateByExampleSelective(@Param("record") MenuInfo record, @Param("example") MenuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIAWW.MENU_INFO
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    int updateByExample(@Param("record") MenuInfo record, @Param("example") MenuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIAWW.MENU_INFO
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    int updateByPrimaryKeySelective(MenuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIAWW.MENU_INFO
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    int updateByPrimaryKey(MenuInfo record);
}