package com.miaww.demoapi.mapper;

import com.miaww.demoapi.model.RoleMenuMap;
import com.miaww.demoapi.model.RoleMenuMapExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleMenuMapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIAWW.ROLE_MENU_MAP
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    long countByExample(RoleMenuMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIAWW.ROLE_MENU_MAP
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    int deleteByExample(RoleMenuMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIAWW.ROLE_MENU_MAP
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    int insert(RoleMenuMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIAWW.ROLE_MENU_MAP
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    int insertSelective(RoleMenuMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIAWW.ROLE_MENU_MAP
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    List<RoleMenuMap> selectByExample(RoleMenuMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIAWW.ROLE_MENU_MAP
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    int updateByExampleSelective(@Param("record") RoleMenuMap record, @Param("example") RoleMenuMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIAWW.ROLE_MENU_MAP
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    int updateByExample(@Param("record") RoleMenuMap record, @Param("example") RoleMenuMapExample example);
}