package com.miaww.demoapi.mapper;

import com.miaww.demoapi.model.UserInfo;
import com.miaww.demoapi.model.UserInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIAWW.USER_INFO
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    long countByExample(UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIAWW.USER_INFO
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    int deleteByExample(UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIAWW.USER_INFO
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIAWW.USER_INFO
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIAWW.USER_INFO
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    int insertSelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIAWW.USER_INFO
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    List<UserInfo> selectByExample(UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIAWW.USER_INFO
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    UserInfo selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIAWW.USER_INFO
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    int updateByExampleSelective(@Param("record") UserInfo record, @Param("example") UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIAWW.USER_INFO
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    int updateByExample(@Param("record") UserInfo record, @Param("example") UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIAWW.USER_INFO
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    int updateByPrimaryKeySelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIAWW.USER_INFO
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    int updateByPrimaryKey(UserInfo record);
}