package com.miaww.demoapi.model;

public class MenuInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIAWW.MENU_INFO.MENU_ID
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    private String menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIAWW.MENU_INFO.MENU_NAME
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    private String menuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIAWW.MENU_INFO.MENU_STATUS
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    private String menuStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIAWW.MENU_INFO.MENU_ID
     *
     * @return the value of MIAWW.MENU_INFO.MENU_ID
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIAWW.MENU_INFO.MENU_ID
     *
     * @param menuId the value for MIAWW.MENU_INFO.MENU_ID
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIAWW.MENU_INFO.MENU_NAME
     *
     * @return the value of MIAWW.MENU_INFO.MENU_NAME
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIAWW.MENU_INFO.MENU_NAME
     *
     * @param menuName the value for MIAWW.MENU_INFO.MENU_NAME
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIAWW.MENU_INFO.MENU_STATUS
     *
     * @return the value of MIAWW.MENU_INFO.MENU_STATUS
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    public String getMenuStatus() {
        return menuStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIAWW.MENU_INFO.MENU_STATUS
     *
     * @param menuStatus the value for MIAWW.MENU_INFO.MENU_STATUS
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    public void setMenuStatus(String menuStatus) {
        this.menuStatus = menuStatus;
    }
}