package com.miaww.demoapi.model;

public class RoleInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MIAWW.ROLE_INFO.ROLE_ID
	 * @mbg.generated  Sat Sep 14 01:53:01 ICT 2019
	 */
	private String roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MIAWW.ROLE_INFO.ROLE_NAME
	 * @mbg.generated  Sat Sep 14 01:53:01 ICT 2019
	 */
	private String roleName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MIAWW.ROLE_INFO.ROLE_STATUS
	 * @mbg.generated  Sat Sep 14 01:53:01 ICT 2019
	 */
	private String roleStatus;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MIAWW.ROLE_INFO.ROLE_ID
	 * @return  the value of MIAWW.ROLE_INFO.ROLE_ID
	 * @mbg.generated  Sat Sep 14 01:53:01 ICT 2019
	 */
	public String getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MIAWW.ROLE_INFO.ROLE_ID
	 * @param roleId  the value for MIAWW.ROLE_INFO.ROLE_ID
	 * @mbg.generated  Sat Sep 14 01:53:01 ICT 2019
	 */
	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MIAWW.ROLE_INFO.ROLE_NAME
	 * @return  the value of MIAWW.ROLE_INFO.ROLE_NAME
	 * @mbg.generated  Sat Sep 14 01:53:01 ICT 2019
	 */
	public String getRoleName() {
		return roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MIAWW.ROLE_INFO.ROLE_NAME
	 * @param roleName  the value for MIAWW.ROLE_INFO.ROLE_NAME
	 * @mbg.generated  Sat Sep 14 01:53:01 ICT 2019
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MIAWW.ROLE_INFO.ROLE_STATUS
	 * @return  the value of MIAWW.ROLE_INFO.ROLE_STATUS
	 * @mbg.generated  Sat Sep 14 01:53:01 ICT 2019
	 */
	public String getRoleStatus() {
		return roleStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MIAWW.ROLE_INFO.ROLE_STATUS
	 * @param roleStatus  the value for MIAWW.ROLE_INFO.ROLE_STATUS
	 * @mbg.generated  Sat Sep 14 01:53:01 ICT 2019
	 */
	public void setRoleStatus(String roleStatus) {
		this.roleStatus = roleStatus;
	}
}