package com.miaww.demoapi.model;

public class RoleMenuMap {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIAWW.ROLE_MENU_MAP.ROLE_ID
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIAWW.ROLE_MENU_MAP.MENU_ID
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    private String menuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIAWW.ROLE_MENU_MAP.ROLE_ID
     *
     * @return the value of MIAWW.ROLE_MENU_MAP.ROLE_ID
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIAWW.ROLE_MENU_MAP.ROLE_ID
     *
     * @param roleId the value for MIAWW.ROLE_MENU_MAP.ROLE_ID
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIAWW.ROLE_MENU_MAP.MENU_ID
     *
     * @return the value of MIAWW.ROLE_MENU_MAP.MENU_ID
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIAWW.ROLE_MENU_MAP.MENU_ID
     *
     * @param menuId the value for MIAWW.ROLE_MENU_MAP.MENU_ID
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }
}