package com.miaww.demoapi.model;

public class UserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIAWW.USER_INFO.USER_ID
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIAWW.USER_INFO.USERNAME
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIAWW.USER_INFO.PASSWORD
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIAWW.USER_INFO.EMAIL
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIAWW.USER_INFO.USER_STATUS
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    private String userStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIAWW.USER_INFO.ROLE_ID
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    private String roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIAWW.USER_INFO.USER_ID
     *
     * @return the value of MIAWW.USER_INFO.USER_ID
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIAWW.USER_INFO.USER_ID
     *
     * @param userId the value for MIAWW.USER_INFO.USER_ID
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIAWW.USER_INFO.USERNAME
     *
     * @return the value of MIAWW.USER_INFO.USERNAME
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIAWW.USER_INFO.USERNAME
     *
     * @param username the value for MIAWW.USER_INFO.USERNAME
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIAWW.USER_INFO.PASSWORD
     *
     * @return the value of MIAWW.USER_INFO.PASSWORD
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIAWW.USER_INFO.PASSWORD
     *
     * @param password the value for MIAWW.USER_INFO.PASSWORD
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIAWW.USER_INFO.EMAIL
     *
     * @return the value of MIAWW.USER_INFO.EMAIL
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIAWW.USER_INFO.EMAIL
     *
     * @param email the value for MIAWW.USER_INFO.EMAIL
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIAWW.USER_INFO.USER_STATUS
     *
     * @return the value of MIAWW.USER_INFO.USER_STATUS
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    public String getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIAWW.USER_INFO.USER_STATUS
     *
     * @param userStatus the value for MIAWW.USER_INFO.USER_STATUS
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    public void setUserStatus(String userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIAWW.USER_INFO.ROLE_ID
     *
     * @return the value of MIAWW.USER_INFO.ROLE_ID
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIAWW.USER_INFO.ROLE_ID
     *
     * @param roleId the value for MIAWW.USER_INFO.ROLE_ID
     *
     * @mbg.generated Sat Sep 14 01:53:01 ICT 2019
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }
}